### ISSUE TITLE
Automatic DI?

### ISSUE THREAD

**Issue by J7mbo** [sarulabs/dingo#1]
Hi! I saw this in a medium post and realised that you did a nicer version of what I did in http://github.com/j7mbo/Goij, in utilising the AST for strings -> structs.

The best thing for me was that I used the `New` convention to automatically initialise structs, recursively. Allow mappings from interfaces to concretes. But the rest basically can be fully automatic.

Would you consider allowing Dingo to become fully automatic, so no configuration needed except for when explicitness is required (interface -> impl)? Any chance of a collaboration on that?

**Comment by J7mbo** [comment]
Looks like this is no longer actively maintained, so closing or now. Feel free to let me know if you want to collaborate on somethings similar in the future!

**Comment by sarulabs** [comment]
Hi ! Sorry I didn't reply sooner. I wanted to look at your project first. But I haven't had time yet.

Concerning `sarulabs/dingo`, the main library is `sarulabs/di`. `sarulabs/dingo` just adds types and some shortcuts to the service definitions. In the end it is a code generator for `sarulabs/di`.

I'm not against making some changes in the library, but I don't see exactly what you have in mind. It would be nice if you could give me some code examples showing how you would like to use the library. There are probably some improvements that can be made to reduce the configuration, but it is probably not that easy.

What will make the configuration not that easy to improve is probably the scope feature. But for me, the two most important features of this library are scopes and close functions. Without them I wouldn't use a dependency injection container in go.

`sarulabs/di` and `sarulabs/dingo` are deeply linked. Ideally I would like it to stay that way. If some improvements to `sarulabs/dingo` do not require code generation, they should be included in `sarulabs/di` too.

I haven't updated the library for a while. I will probably update it soon to use the latest version of `sarulabs/di`. The library also relies on `GOPATH`, so I also need to get rid of that requirement.

The thing is when I created `sarulabs/dingo`, this was a huge improvement to `sarulabs/di` because it handled the errors a lot better. But it is no longer the case. And `sarulabs/dingo` has flaws :
- The configuration allows shortcuts, but they make the configuration more complex that what I would like it too be.
- Generating the code doubles the "compilation" time in a development environment

Improving these two flaws would be really nice.
