### ISSUE TITLE
Add Put method, which will replace key in map, but not value by pointer

### ISSUE THREAD

**Issue by MetalRex101** [sarulabs/dingo#9]
Sarulabs, i really grateful for adding the Fill method to container. I found out how does it works. But it is not the thing i need.

I have the test function, where i want to get some destination service with all dependencies resolved. But i don't need real repository to be resolved as dependency of userFetcher. What i do want is to place userRepoMock to container before resolving my service. So when later i will get my destination service, it will depend on Mock service instead of real one.
```
func test() error {
	container, err := dic.NewContainer(dingo.App)
	if err != nil {
		return err
	}

	userRepoMock := user.RepoMock{}

	if err := container.Fill("user-repository", &userRepoMock); err != nil {
		return err
	}

	fetcher := container.GetUserFetcher()
        // here fetcher depend on mock, not on real userRepository
	fmt.Println(fetcher)

	return nil
}
```

Is that possible to add some kind of `Put` method, which will replace existing object?

I see 2 possible ways to achieve that:
1. Add to definition field like: Redefinable. If that field is true, type safe Put method will be generated for that definition.
2. Add generic Put method, which will check for the same type or for the same interface. Checking is optional, but it will make errors more verbose.

**Comment by sarulabs** [comment]
I checked your code and it is not a solution that I want to integrate.

The reason is that you added things in `generation/di`. Which is bad because I plan to remove this in the `v4` (`sarulabs/di` would be loaded as a module).

If you want to make changes in this directory, they have to be made in `sarulabs/di` first.

But what you want to do has already been asked for `sarulabs/di`.

This is achieved by overriding definitions in the `Builder`.

```go
b, _ := di.NewBuilder()
b.Add(myDefinitions...)
b.Add(myMockDefinition)
ctn := b.Build()
```

And that is not possible in dingo because the container is generated. So I did not see the point of adding a Builder.

If this feature were to be added in dingo, I would like it to be similar to how it works in di.

```go
// For the moment there is only one way to create the container.
func NewContainer(scopes ...string) (*Container, error) {
    // ...
}

// While keeping NewContainer for convenience,
// the idea would be to add a NewBuilder method
// to create a builder accepting definition overriding.
func NewBuilder(scopes ...string) (builder, err) {
    // ...
}

// It would have the same methods as the one in di.
// Including the Add method.
// But I do not think it would be possible to check the types here.
func (b *builder) Add(defs ...di.Def) error {
    // ...
}

// A Put method may be added here.
// But it should be implemented in sarulabs/di first.
// The name may be Set instead of Put because I think it already existed in a previous version of sarulabs/di (I would need to check).
// Checking the type of the object is probably doable here.
func (b *builder) Set(name string, obj interface{}) error {
    // ...
}
```

If this solution seems good to you, I can work on this in the coming days. If you want to work on this yourself, I can detail the solution a bit more. And give you more information about how to contribute to the project (there is no documentation at the moment and it is not that obvious).

Also I talked about a v4. I did not plan to make the changes right now, but as you made me dive into the code, I may implement them. The changes would be:

- Load the sarulabs/di code through a module (right now the code is copied manually in this repo, and then included in the generated code).
- The definitions are also copied in the generated code right now. I has little benefits. The definitions could be used in place.
- Add a library to create your own dingo command. This would be the new recommended way to use dingo. This would fix the dingo version in a project for the command and the code.

**Comment by MetalRex101** [comment]
Thank you for the reply!
While add definition is seems to be valid for the case of tests, it looks like, there is some otherhead, because mock doesn't have any dependencies. Also if no definiton need your mock, there is no sense to create definition for that mock. So, as i see, there is only one condition for mock to replace existing object - it should implement the same interface as replaced object.
I don't really see any other application for the `Put`/`Set` method or definition replacement but for tests.
I would be very greatful to you for adding any solution for overriting definitions or generated container objects.
It also would be nice to create contribution guide too.

**Comment by sarulabs** [comment]
In the `v4`, there is now a `NewBuilder` function in the generated code. It let you `Set` an object in the container. There is no type check though.

**Comment by MetalRex101** [comment]
You are the best! Thank you!
